version: 2.1

executors:
  java-executor:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    working_directory: ~/repo

jobs:
  build:
    executor: java-executor
    steps:
      - checkout

      # Cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # Run tests
      - run:
          name: Run tests
          command: mvn test

      # Save test results
      - store_test_results:
          path: target/surefire-reports

      # Save build artifacts
      - store_artifacts:
          path: target/*.jar

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
